### PR TITLE
Some new customization options and a fix for layer 2 bridge interfaces

### PR DESCRIPTION
**Pull request by brianreumere**
I'd been thinking about writing a similar script and came across kvm-install-vm and it's so great! VMs come up so quickly compared to using kickstart. I added some options to it that are useful for my KVM setup. There's the ability to choose: 

* Graphics type (I prefer VNC) and graphical console port (auto by default)
* Username for the additional user that's created (defaults to $USER)
* A file with custom runcmd contents in it (file has to be indented properly, two spaces at the beginning of each line)

I also added a check for the bridge interface status file in /var/lib/libvirt/dnsmasq and assume the bridge interface specified is a layer 2 bridge if the status file doesn't exist (I use mostly layer 2 bridges for my KVM VMs, so without this the script got stuck in a loop waiting for the IP of the new VM).

I added a weird workaround for getting the correct port number for the graphical console when using VNC, because apparently the port number that virsh domdisplay reports is offset from 5900 (e.g. domdisplay shows port 2, actual port number is 5902).

I'm happy to maintain my own fork with these features if you don't want to merge this, but I thought I'd offer these changes for feedback either way. Thanks!

-Brian

### CODE REVIEW

**Comment by giovtorres** [comment]
Hi @brianreumere, I welcome contributions!  Did you manage to run the tests after the changes?

**Comment by brianreumere** [comment]
It looks like my version of virt-install (1.4.1 on CentOS 7.4) doesn't support fedora26, fedora27, or debian9, so those tests fail. Some changes I had to make to get the other tests to pass:

* For the attach-disk tests I had to change the DISKDIR variable in kvm-install-vm to use ${IMAGEDIR}/${VMNAME} instead of ${HOME}/virt/images/${VMNAME} because I use a non-default IMAGEDIR
* For the hostname resolution test I had to increase the sleep time to 45 seconds because it regularly took between 30 and 40 seconds for hostname resolution to start working after launching a VM
* For the hostname resolution to consistently work I created a unique VMNAME in the vmname.bash file and loaded it into check_scripts.bats (otherwise batstestvm would resolve to an old/stale IP address if I quickly re-ran test.sh)
* For the cloud-init test I had to add the centos username to the ssh command because I'm running kvm-install-sh as root and the centos VM doesn't allow root login
* For the last test (check destroyed VM files) I created imagedir.bash and loaded it into check_scripts.bats because otherwise it was looking in ${HOME}/virt/images/${VMNAME} instead of under the custom IMAGEDIR I'm using

Let me know how this looks.

**Comment by brianreumere** [comment]
I also noticed the description text for attach-disk was a duplicate of the description for the remove subcommand so I changed that.

**Comment by brianreumere** [comment]
Sorry to keep piling onto a single pull request, but I ended up removing the -r option to include additional runcmd items, and instead added a -s option to include a shell script. This means the user-data is composed as a [MIME multi-part archive](https://cloudinit.readthedocs.io/en/latest/topics/format.html) now instead of only cloud-config. (Another useful example of MIME multi-part archive is [in the AWS docs](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/bootstrap_container_instance.html#multi-part_user_data).) I successfully ran test.sh with these changes (with the exception of the fedora26, fedora27, and debian9 tests I mentioned before) and also was able to launch an instance with a custom script (see https://streamable.com/gt6hv for a video example).

**Comment by brianreumere** [comment]
Added an autostart option too.

**Pull request merged**
