### PR TITLE
Added support for .kiv-distros.json

### LINKED ISSUE #51: Support to custom list of distros
My use case for kvm-install-vm is to perform test run in multiple versions of a given distro (centos, fedora and rhel). While I don't think it would make sense to create a PR to add centos-1611, centos1811, centos1907, etc., those names are meaningful and helpful in my tests.

For that reason I'd like to suggest that the mapping of distros could be customized in .kvirc or somewhere else. 

Thanks!

### PR DESCRIPTION
**Pull request by seocam**
* Closes #51

### CODE REVIEW

**Comment by seocam** [comment]
I've changes quite a few things around in this PR. 

1. Added support to .kiv-distros.json where users will be able to build their own aliases for their vms.
1. OS_TYPE and DISK_FORMAT are the same for all current images so I've set a default (user can override but it's all in a single place.
1. Moved NETRESTART, SUDOGROUP and CLOUDINITDISABLE to be configured case by case but the default is set by OS_VARIANT.
1. Added validation to ensure QCOW OS_VARIANT IMAGE_URL LOGIN_USER are always set.
1. Fixed indentation.

I think that's all I've touched.

The only thing I didn't change that I don't quite know how to solve is the if DISTRO_NAME that checks for amazon linux and a specific version of ubuntu to do something different. In order to have my approach fully functional there shouldn't be exceptions by distro (by os_variant would be fine).

Please, let me know what you think.

**Comment by seocam** [comment]
That's my use case for that [not merged yet]: 

* https://github.com/seocam/ansible-freeipa/blob/202843e66627ab93d71b1c5d473c07865d6d5981/tests/README.md
* https://github.com/seocam/ansible-freeipa/blob/202843e66627ab93d71b1c5d473c07865d6d5981/tests/create-test-vm.sh

**Comment by seocam** [comment]
I've also added docs on the dependencies for Debian-based systems.

**Comment by giovtorres** [comment]
I'm still looking at this. One thing that comes to mind so far is JSON vs YAML. I've always felt YAML is an easier to use human interface over JSON. Could we use YAML and [yq](https://github.com/kislyuk/yq) over JSON and jq? Thoughts?

**Comment by seocam** [comment]
I also prefer yaml over json!

The reason why I decided to use jq was because the package was available on
both debian and Red Hat based systems.
Unfortunately that's not true for yq.

**Comment by giovtorres** [comment]
I like this idea a lot. I haven't had a chance to pull it down and test it locally, but I will!

**Comment by giovtorres** [comment]
I thought about this some more and I just have some reservations about a json interface. I have some ideas on how to provide a better interface, but requires some refactoring.

**Comment by giovtorres** [comment]
Closing this PR for now. I like this feature and would like to shuffle things around a bit first to make the implementation a little more user friendly. Thanks!

**Pull request closed without merging**
